# Config for https://github.com/release-drafter/release-drafter
name-template: 'Play SOAP $NEXT_PATCH_VERSION'
tag-template: '$NEXT_PATCH_VERSION'

categories:
  - title: ':rocket: Features'
    labels:
      - 'enhancement'
  - title: ':bug: Bug Fixes'
    labels:
      - 'bug'
  - title: ':toolbox: Maintenance'
    labels:
      - 'maintenance'
  - title: ':dart: Dependencies'
    labels:
      - 'dependencies'

template: |
  # :mega: Play SOAP $NEXT_PATCH_VERSION released!

  We are pleased to announce the release of SOAP module for [Play](https://playframework.org/) framework.

  ## :green_book: What’s Changed

  $CHANGES

  ## :bow: Credits

  Thank you @scala-steward for the actual versions of dependencies :heart:

  Special thanks to the following contributors who helped with this release: $CONTRIBUTORS
