queue_rules:
  - name: default
    conditions:
      # Conditions to get out of the queue (= merged)
      - check-success=Check / Code Style
      - check-success=Check / Tests

pull_request_rules:
  - name: Merge PRs that are ready
    conditions:
      - check-success=Check / Code Style
      - check-success=Check / Tests
      - check-success=typesafe-cla-validator
      - "#approved-reviews-by>=1"
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
      - label!=status:block-merge
      - label=status:merge-when-green
    actions:
      queue:
        method: merge
        name: default

  - name: Delete the PR branch and remove label after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}
      label:
        remove: ["status:merge-when-green"]

  - name: Labeling for Scala Steward PR's
    conditions:
      - author=scala-steward
    actions:
      label:
        add: ["dependencies"]