language: scala

git:
  depth: false # Avoid sbt-dynver not seeing the tag

before_install: curl -Ls https://git.io/jabba | bash && . ~/.jabba/jabba.sh
install: jabba install $(jabba ls-remote "adopt@~1.$TRAVIS_JDK.0-0" --latest=patch) && jabba use "$_" && java -Xmx32m -version
env:
  matrix:
    - TRAVIS_JDK=8
  global:
    # NOTE: Very important don't forget about escaping symbols.
    # See https://docs.travis-ci.com/user/encryption-keys#note-on-escaping-certain-symbols

    # GITHUB_TOKEN needs for publishing documentation to GitHub Pages. See https://docs.travis-ci.com/user/deployment/pages/
    # travis encrypt --pro GITHUB_TOKEN="*****"
    - secure: "TzcfXRgEhmMPG8EH5RBlOa6YJ6HnYdQYAJ7OIEu84ig/b5d/vodkTW0uy7n+nqUb9HyXBs3dlE/Yfi1LHDUy/UVtmvCXZcvywduW64K38m1hG3M2jZ3TIG9Id5jAufMg6Z734wzH1v2tIG0zrZtcq05lXPzKFLutPOsdbYgUwKH8liBzRMGs/UlqnxVdTWLrL43hPoTQBIPT99g9/wja+dXnvE1+aRoiMI4VWGumhRdijoX/69gKjnSgwPBrksU7AZkm3k+UDtg2r/+To95aaCj95AanUUjiNWR+gbeTB81DhzTyqccqw5Kl4nP2gJkOLFNenfcRHSY7V2M1oiGcnWmTCEW5pj2lAEUpDiqeqTSZYme1XZPPfwHlXsu3Pyx/GZ+hwRvpbAHR4I+4jyDH+mQRZ+C4dNx6s2QjYah/rnmv9uZ8TpnZ7MNqWIH/wP6VSf8ouC5PqO0i8GVqYfT0kp0LCme3M++OZipC+8xRzXKJLDxl2Mi3h34f1rtQQkJsn0ff4qRcnmXvhCLOa0szgL849ebVcHXCC5WkYVYg7wxdHbxH0e/kl2ujun19cl6Sh1YBkTNiwK60TOJO/W4JGNuQRXPAiuo+9nX/3oipl5mfN7Uda3u4kcOMyDexc5+oBFUsstfR2lSaemcpWgSbmJskJ0X4d3LSOdoShgR4xG4="

    # Settings for publishing artifacts to Bintray. See https://github.com/sbt/sbt-bintray
    # NOTE: BINTRAY_USER is a username on Bintray, not email.
    # travis encrypt --pro BINTRAY_USER="*****"
    - secure: "hpJrvh2IS64hyKFs83FDJ15jU0pwqDWtd/coMYx5wWZwPFk0T0ozzbTLVJFN33ROMT9qkh2e9pL4AehgjT01+EAmz/Wz24smnXFZV/w7lh9ZgMfSyJqrhWjk171xbmG6UUL9IfFSqT09VQdFqL5JZp20jQ3oxcOCL8zRJwSiUJH0ZD6AF1F67iFZaDFs+O3nwqeNHFRDLn1c7Sl+9CKqheqvH+QfXgC35eBrz5fs/Yw9fqGylNWmVGLNiNkuFw7bg4b3Q5mCvyrzBIRgmjwxZV79/fzbFNvia0wiRgmjEIiLRs1/gH4THZW0mZodsm587mpflVJJ0z2BZwfQWNKh5pDSrUtl9rOcm78iuqDjIGerCJbeUNblW8e6wR9PunNE38mYvmvi9S79e0uWHxQkY3YdWBDYcbiXfadoWE/iszcZBf8ol0f6optwDifOUcn5SygOo3trZQXze/rjHBKph9tNrh+KO+qMzslHzJb00lqszhv1blolYDzIDwDTLkSoIuX0KsbzV5YQuQ5PSKQu3vnrNggaxByKL6aS2ons7ecAmZNXITyWTg3fRM6XgZ/0wBKz+6McPZZOmMj7On/N4wuzYy6cHIDKSBKe0218MXtWjm4/Owog9hXwnIkeBoVxI2XwL9DgNVi8jaMDJzKbpDAuJabcEtObDl0XPEwUQLA="
    # NOTE: BINTRAY_PASS is a API Key, not password. See https://www.jfrog.com/confluence/display/BT/Uploading#Uploading-GettingyourAPIKey
    # travis encrypt --pro BINTRAY_PASS="*****"
    - secure: "a/BIiPkrgECjW5QUrt8N4LuL6ENj9Anjcxux7Nm8myTBXzYd+SCuEdAFBTQg6Jd9w6osWBCQdPfsSZMZSazYpE+b/CqDkYoLVPEE8BvffPSWEvCYenSfKYNHvpbW4rY834wDW6dsDZgBLpLnWlrEufR6ITUaUPxdb2ENcSnTo29aQqz3T3ZUQiSfoHG3PifeVKSQdWeJlr/yB0GD5ShuaUegipzPNY6+7uz77hC9cPScvecIR19YOyyLLpWWHPVm0GwiHVfeNwOUrfq1fhuduGRI2UK2rL17Y9DKaAmsRyzaTTKJ2VaCDTp/gUHPso0N1fI77+mhEp6JO6YT6Wqh57/9Fgn2Qdc2p1daJejbQykRNIY/LyMUeMcRLUPwepipRlB/LCpdH1RuZZi9f8kSbk+n8HrfIfk14DMhjDMQ3MB0MmuR0drsJ5C2tpLo26dZFrv8xRqQihqwbf9XthB38h/wLlUyGX5gfj78g0UjPN38aEq6rNAznABToATnoKKHFnYLoY25pdAoCngT8Qp32umQ5TJtbHGLh02rq8BmBu7he5m29A5y4J4D3GR7R9qGjRbNRvlhNeyThMoihKnHYBiqbVEYi4Ry+U6eCxMzApODbMarVQdI7LfKIx8Hj3PfpN2FnXNpLvuqcuTKh2GvuC4YGAVCsXHdgBm2SNs7htM="


script:  
  # Code validations
  - scripts/validate-code-style || travis_terminate 1; 
  - sbt +test || travis_terminate 1; 
  - sbt +publishLocal || travis_terminate 1; 
  - sbt plugin/scripted || travis_terminate 1; 
  # Generate documentation
  - sbt docs/webStage || travis_terminate 1; 

deploy:
  # Publishing documentation
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: docs/target/web/stage
    target_branch: gh-pages
    on:
      branch: master

  # Publishing release and snapshot artifacts
  - provider: script
    skip_cleanup: true
    script: scripts/publish
    if: repo = akka/akka-projection AND ( ( branch = master AND type = push ) OR tag =~ ^v )

cache:
  directories:
  - $HOME/.cache/coursier
  - $HOME/.jabba/jdk
  - $HOME/.ivy2/cache
  - $HOME/.sbt/
