language: scala

git:
  depth: false # Avoid sbt-dynver not seeing the tag

before_install: curl -Ls https://git.io/jabba | bash && . ~/.jabba/jabba.sh
install: jabba install $(jabba ls-remote "adopt@~1.$TRAVIS_JDK.0-0" --latest=patch) && jabba use "$_" && java -Xmx32m -version
env:
  matrix:
    - TRAVIS_JDK=8
  global:
    # NOTE: Very important don't forget about escaping symbols.
    # See https://docs.travis-ci.com/user/encryption-keys#note-on-escaping-certain-symbols

    # GITHUB_TOKEN needs for publishing documentation to GitHub Pages. See https://docs.travis-ci.com/user/deployment/pages/
    # travis encrypt --pro GITHUB_TOKEN="*****"
    - secure: "TzcfXRgEhmMPG8EH5RBlOa6YJ6HnYdQYAJ7OIEu84ig/b5d/vodkTW0uy7n+nqUb9HyXBs3dlE/Yfi1LHDUy/UVtmvCXZcvywduW64K38m1hG3M2jZ3TIG9Id5jAufMg6Z734wzH1v2tIG0zrZtcq05lXPzKFLutPOsdbYgUwKH8liBzRMGs/UlqnxVdTWLrL43hPoTQBIPT99g9/wja+dXnvE1+aRoiMI4VWGumhRdijoX/69gKjnSgwPBrksU7AZkm3k+UDtg2r/+To95aaCj95AanUUjiNWR+gbeTB81DhzTyqccqw5Kl4nP2gJkOLFNenfcRHSY7V2M1oiGcnWmTCEW5pj2lAEUpDiqeqTSZYme1XZPPfwHlXsu3Pyx/GZ+hwRvpbAHR4I+4jyDH+mQRZ+C4dNx6s2QjYah/rnmv9uZ8TpnZ7MNqWIH/wP6VSf8ouC5PqO0i8GVqYfT0kp0LCme3M++OZipC+8xRzXKJLDxl2Mi3h34f1rtQQkJsn0ff4qRcnmXvhCLOa0szgL849ebVcHXCC5WkYVYg7wxdHbxH0e/kl2ujun19cl6Sh1YBkTNiwK60TOJO/W4JGNuQRXPAiuo+9nX/3oipl5mfN7Uda3u4kcOMyDexc5+oBFUsstfR2lSaemcpWgSbmJskJ0X4d3LSOdoShgR4xG4="

    # Settings for publishing artifacts to Bintray. See https://github.com/sbt/sbt-bintray
    # NOTE: BINTRAY_USER is a username on Bintray, not email.
    # travis encrypt --pro BINTRAY_USER="*****"
    - secure: "pG1YuTuF076djAQfkY3ig5XebEUSqbPTdg9U3+rLN/rFL+MAVbccUj3SNyP8LRc23Bd99i2q7Oo6brNzLdr3XIEr/UbIIj2Ur/t0IcGla4RE68AqsJK8LcyKKel419IZrpGlmqwTyNOkIZs3o8rauU7PUYwZsxgKxN+7mrdYJpd0JEf6BaW/tTMx9ybV2+u+0RvXnACDYYlluoStkEl2FNIHhI9jKKp3NXRfFAkFvCxF+KqyWDnlCIx8pyfKT8pxKRewl0yr0O90gq7h7gHTPuwsNQgNJPWp7M4lXr/ItPDe80qQnapQcAbIwv1w6v/WqNyGhznOK8S63w48Pkobjasycj7r4nEmH4Tjb199uMs3mPOLYDJxqR4hbMT/4LWL2/XuhQEbXgCew5Rjbd5wt+ZEs4gCbtznlBgQ9qD2PVHWWo5TDRm9g99S0RGTKMJ1nxGl25z2kDJPigoAoaNuqgUtAuulNXtscHZgDLGVx84SODlWHQzUf7M3jS2NVCzl8Ig0CbWOPBgGqdd+XX2blc7IBDGYQPUMiyHAtRDF3lPq1BityghwQg5a6ToRn3JOlkrqIzCW1BonEt6S1LXFnLFMegW5sZOODuyxPoYCdXpHUAqB2WfdogqwkPicvvk+kiszdd3TBhWAUiQvk7Grvzvz775/QRIS7SsHf2R9YCY="
    # NOTE: BINTRAY_PASS is a API Key, not password. See https://www.jfrog.com/confluence/display/BT/Uploading#Uploading-GettingyourAPIKey
    # travis encrypt --pro BINTRAY_PASS="*****"
    - secure: "AMX8SEP6hDywa5QRwVUNYCE55gYW1RHLs6jkQ/NwVJpX7fOPNynkbyLvau/snZzYvUYqapX8ntUvKmDHwHLceHfAt14B+ehg4Z18C203gr5VsOJwfmzttd3Ohl4eoUETbE+R2sfWLDEINkf9+v6pvYC6bb91o2SDG8sxiLt3tyCMTb/5/V+cYU5go1e8+LXVPVRZctqpsm9dK5ajdHk5SJWQI+Wnd1ADnPdrbN4pFEPgSHIybEPuntn9SNbdyXuRSsqKoeTzkblo9Q/DAtjLb19SS0+wG8BDLSPPqptaByVAPR/bLyqy3bTjm9rTdLxXq2i9K2I7o7VbY1XnhhbOrAcbVnUeVNTovNSMhCaAggYbyA3HC3nVlas4I9qP0jDXCrkVLK9DA/CSVBYnRyu5L9jcg3EbQyhAhGxUoR2cZN/qY40HgeueRCYWvRWo6G8Wswds5uAn2QLEHnpX7fAuGd7XNooo4UN4CjGYI6R0k10v7I9InZSGrmcCHJ7MZgaFoYXXEEJcJcWSFxyAsskxLuG6cTrLDbp2czI5jHYANvvoQw3w3h7ulOdeXDkEnzDVDm8HLJW43FazLYVoMuwIYLmkFhjhcWWCBUv8p/hFCae3QOXgLrB4WlAAAUC6A9aYKmiS3Xh2q4R4DOQQYb7f5eYXfe1Owg+Br0Gh5THG28o="


script:
  - echo "skip scipts" # TODO: remove before merge
  # Code validations
#  - scripts/validate-code-style || travis_terminate 1; TODO: uncomment before merge
#  - sbt +test || travis_terminate 1; TODO: uncomment before merge
#  - sbt +publishLocal || travis_terminate 1; TODO: uncomment before merge
#  - sbt plugin/scripted || travis_terminate 1; TODO: uncomment before merge
  # Generate documentation
#  - sbt docs/webStage || travis_terminate 1; TODO: uncomment before merge

deploy:
  # Publishing documentation
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: docs/target/web/stage
    target_branch: gh-pages
    on:
      branch: master

  # Publishing snapshot artifacts
  - provider: script
    skip_cleanup: true
    script: scripts/publish-snapshots
    on:
      branch: master
      tags: false # Disable publishing for release tags

  # Publishing release artifacts
  - provider: script
    skip_cleanup: true
    script: scripts/publish-release
    on:
      branch: releases # TODO: remove before to merge
#      tags: true  TODO: uncomment before merge

cache:
  directories:
  - $HOME/.cache/coursier
  - $HOME/.jabba/jdk
  - $HOME/.ivy2/cache
  - $HOME/.sbt/
