_extends: .github:.github/release-drafts/increasing-patch-version.yml
categories:
  - title: ':rocket: Features'
    labels:
      - 'enhancement'
  - title: ':bug: Bug Fixes'
    labels:
      - 'bug'
  - title: ':toolbox: Maintenance'
    labels:
      - 'maintenance'
  - title: ':dart: Dependencies'
    labels:
      - 'dependencies'

header: |
  # :mega: Play SOAP $NEXT_PATCH_VERSION released!

  We are pleased to announce the release of SOAP module for [Play](https://playframework.org/) framework.

template: |
  ## :green_book: What’s Changed

  $CHANGES
