name: Check

on:
  pull_request:

concurrency:
  # Only run once for latest commit per ref and cancel other (previous) runs.
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-code-style:
    name: Code Style
    uses: playframework/.github/.github/workflows/sbt.yml@v1
    with:
      cmd: sbt validateCode

  check-docs:
    name: Docs
    uses: playframework/.github/.github/workflows/sbt.yml@v1
    with:
      cmd: sbt docs/webStage

  tests:
    name: Tests
    needs: # Waiting more lightweight checks
      - "check-code-style"
      - "check-docs"
    uses: playframework/.github/.github/workflows/sbt.yml@v1
    with:
      cmd: sbt +test

  scripted-tests:
    name: Scripted tests
    needs: # Waiting more lightweight checks
      - "tests"
    uses: playframework/.github/.github/workflows/sbt.yml@v1
    with:
      cmd: sbt +publishLocal plugin/scripted

  finish:
    name: Finish
    needs: # Should be last
      - "scripted-tests"
    uses: playframework/.github/.github/workflows/rtm.yml@v1
