name: Pull Requests

on:
  pull_request:

concurrency:
  # Only run once for latest commit per ref and cancel other (previous) runs.
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-code-style:
    name: Check / Code Style
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0

      - name: Set up JDK 8
        uses: olafurpg/setup-scala@v13
        with:
          java-version: adopt@1.8

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6.2

      - name: Code validations
        run: sbt +headerCheckAll scalafmtCheckAll scalafmtSbtCheck javafmtCheckAll

  check-tests:
    name: Check / Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0

      - name: Set up JDK 8
        uses: olafurpg/setup-scala@v13
        with:
          java-version: adopt@1.8

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6.2

      - name: Tests
        run: sbt +test

      - name: Scripted tests
        run: sbt +publishLocal plugin/scripted

  check-docs:
    name: Check / Docs
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0

      - name: Set up JDK 8
        uses: olafurpg/setup-scala@v13
        with:
          java-version: adopt@1.8

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6.2

      - name: Generate documentation
        run: sbt docs/webStage
